apiVersion: v1
kind: Service
metadata:
  name: {{ include "koopjs.fullname" . }}
  labels:
    {{- include "koopjs.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: {{ .Values.service.name }}
      nodePort: {{ .Values.service.nodePort}}
  selector:
    {{- include "koopjs.selectorLabels" . | nindent 4 }}
